linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - ifshort
    - golint
    - scopelint
    - maligned
    - interfacer
    - contextcheck
    - rowserrcheck
    - sqlclosecheck
    - structcheck
    - wastedassign
    - deadcode
    - nosnakecase
    - varcheck